### ISSUE TITLE
把里面的transformer换成lstm   模型的大致框架是不会发生变化的吧

### ISSUE THREAD

**Issue by SomeoneNotLikeYou** [cuhksz-nlp/AESINER#10]

**Comment by SomeoneNotLikeYou** [comment]
最后的pos_value_embedding、dep_value_embedding、chunk_value_embedding 、key_pos_embed、key_pos_embed、key_chunk_embed 都是基于随机生成的nn.embedding嘛  有用的是matrix吗

**Comment by nyy477** [comment]
hello，同学，感谢对此项目的关注。这几个embedding是用来实现key-value memory network的，是有用的matrix，虽然是随机初始化，但是是在训练过程中进行更新的。pos代表词性标注、chunk代表成分句法、dep代表依存句法。
