### ISSUE TITLE
how to preprocess the original Ontonote4.0

### ISSUE THREAD

**Issue by tyistyler** [cuhksz-nlp/AESINER#4]
Excuse me, could you please release how to preprocess the original Ontonote4.0, because I can't get the information from the https://github.com/yhcc/OntoNotes-5.0-NER..
Thanks!!!

**Comment by nyy477** [comment]
If you do not have the original files of OntoNote4.0, you can refer to  https://github.com/ShannonAI/glyce/blob/master/docs/dataset_download.md to get the preprocessed data.
