### ISSUE TITLE
如何获取tencent_unigram.txt文件？

### ISSUE THREAD

**Issue by xqrshine** [cuhksz-nlp/AESINER#8]
您好，我想问一下tencent_unigram.txt文件在哪里怎么获取呢？或者您可以发给我一份么？

**Comment by ume-technology** [comment]
兄弟,  你找到这个文件了吗?   有的话能不能分享一份给我呢?   我实在是找不到哪里可以下载才迫不得已伸手要的,  或者给我个链接, 我自行下载.   这是我邮箱:   swhardbewell@qq.com     感谢!
